config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get "/home/about" => "homes#about" , as: "about"

  resources :books, only: [:new, :create, :update, :edit, :index, :show, :destroy]
  resources :users, only: [:index, :show, :edit, :update]

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

   has_one_attached :image
   belongs_to :user

   validates :title, presence: true
   validates :body, presence: true, length: { maximum: 200 }

   def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
   end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }


  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]


  def new
    @book = Book.new
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
    @users = User.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
   if @book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)
   else
    @books = Book.all
    @user = current_user
    render :index

   end
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
   if @book.update(book_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
   else
    render :edit
   end
  end


  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/todolists_controller.rb
def index
    puts "作成したキー #{ENV['SECRET_KEY']}"
    @lists = List.all
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guestuserでログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
       render :edit
    else
       redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
   if @user.update(user_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to user_path(@user.id)
   else
    render :edit
   end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
  <div class="col-md-3">

    <h2>User info</h2>
      <p><%= image_tag user.get_profile_image(100,100) %></p>
        <table class="table">
         <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
         </tbody>
        </table>

        <div class="row">
         <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
         <% end %>
        </div>

          <h2 class="mt-3">New book</h2>
            <%= form_with model: book do |f| %>

          <div class="form-group">
          <label for="book_title">Title</label>
            <%= f.text_field :title %>
          </div>

          <div class="form-group">
          <label for="book_title">Option</label>
            <%= f.text_area :body %>
          </div>

          <div class="form-group">
            <%= f.submit 'Create Book', class: "btn btn-success" %>
          </div>
            <% end %>

　 </div>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Update Book' %>

<% end %>

 <%= link_to "Show", book_path(@book.id) %>

 <%= link_to "Back", books_path %>

app/views/books/index.html.erb
 <div class="container px-5 px-sm-0">
   <div class="row">

   <%= render 'books/list', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">

     <% if @book.errors.any? %>
     <%= @book.errors.count %>errors prohibited this obj from being saved:
     <ul>
     <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
      </ul>
     <% end %>

      <h2>Books</h2>

          <table class="table table-hover table-inverse">
            <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
            </thead>
            <% @books.each do |book| %>
            <tbody>
              <tr>
                <td>
                 <%= link_to user_path(book.user.id) do %>
                 <%= image_tag book.user.get_profile_image(100,100) %>
                 <% end %>
                </td>
                <td>
                 <%= link_to book_path(book.id) do %>
                 <%= book.title %>
                 <% end %>
                </td>
                <td>
                 <%= book.body %>
            <% end %>
                </td>
              </tr>
            </tbody>
          </table>

     </div>
   </div>
 </div>

app/views/books/new.html.erb
<h>NewBooks</h1>
  <%= form_with model: @book do |f| %>

    <h4>Title</h4>
      <%= f.text_field :title %>
    <h4>Option</h4>
      <%= f.text_area :body %>
    <%= f.submit 'submit' %>
  <% end %>

app/views/books/show.html.erb
 <div class="container px-5 px-sm-0">
   <div class="row">
     <%= render 'books/list', user: @user,book: @book_new %>

      <div class="col-md-8 offset-md-1">

        <h2>Book detail</h2>
        <table class="table">
         <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
              <%= image_tag @user.get_profile_image(100,100) %>
              <p><%= @book.user.name %></p>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book.id) do %>
              <p><%= @book.title %></p>
              <% end %>
            </td>
            <td>
              <p><%= @book.body %></p>
            </td>
            <td>
               <% if @book.user == current_user %>
               <div class="btn btn-sm btn-success">
               <%= link_to "Edit", edit_book_path(@book.id) %>
               <% end %>
               </div>
            </td>
            <td>
                <% if @book.user == current_user %>
                <div class="btn btn-sm btn-danger">
                <%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
                <% end %>
                </div>
            </td>
          </tr>
         </tbody>
        </table>
      </div>
     </div>
    </div>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>
      !!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">

        <h1>welcome to<i class="fas fa-book"></i>
        <strong>Bookers</strong>
        !!
        </h1>
      <P>In<i class="fas fa-book"></i>
      <strong>Bookers</strong>
      ,
      </p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>

      <div class="btn-wrapper col-10 mx-auto">
         <div class="row">
          <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, class: "btn btn-secondary btn-sm btn-block mb-3 sign_in", method: :post %>
        </div>

      <div class="row">
      <%= link_to new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" do %>Log in<% end %>
      </div>

      <div class="row">
      <%= link_to new_user_registration_path, class: "btn btn-success btn-sm btn-block md-3 sign_up" do %>Sign up<% end %>
      </div>

      </div>

      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Bookers2Ver2</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="true" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown" style>
        <ul class="navbar-nav ml-auto">

        <% if user_signed_in? %>


          <li>
          <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
          <i class="fas fa-home"></i>Home
          <% end %>
          </li>

          <li>
          <%= link_to users_path, class: "nav-link text-light" do %>
          <i class="fas fa-users"></i>Users
          <% end %>
          </li>


          <li>
          <%= link_to books_path, class: "nav-link text-light" do %>
          <i class="fas fa-book-open"></i>Books
          <% end %>
          </li>

          <li>
          <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
          <i class="fas fa-sign-out-alt"></i>Log out
          <% end %>
          </li>

        <% else %>

          <li>
          <%= link_to root_path, class: "nav-link text-light" do %>
          <i class="fas fa-home"></i>Home
          <% end %>
          </li>

          <li>
          <%= link_to about_path, class: "nav-link text-light" do %>
          <i class="fas fa-link"></i>About
          <% end %>
          </li>

          <li>
          <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
          <i class="fas fa-user-plus"></i>Sign up
          <% end %>
          </li>

          <li>
          <%= link_to new_user_session_path, class: "nav-link text-light" do %>
          <i class="fas fa-sign-in-alt"></i>Log in
          <% end %>
          </li>

        <% end %>

        </ul>
      </div>
      </div>
      </nav>
    </header>

    <main>
    <p><%= flash[:notice] %></p>
    <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
    </body>
</html>

app/views/users/edit.html.erb
<h2>User info</h2>

<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this user from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>



<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
   <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>

  <label for="inputImage">ProfileImage</label>
   <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>

  <label for="inputIntroduction">Introduction</label>
   <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction", placeholder:"紹介"%>


  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
   <div class="row">
    <%= render 'books/list', user: @user, book: @book %>
   <div class="col-md-8 offset-md-1">

     <h1>Users</h1>

        <table class="table table-hover table-inverse">
          <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
          </thead>
          <% @users.each do |user| %>
          <tbody>
          <tr>
            <td>
              <%= image_tag user.get_profile_image(100,100) %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td>
              <%= link_to 'Show', user_path(user.id) %>
          <% end %>
            </td>
          </tr>
         </tbody>
      </table>
   </div>
   </div>
 </div>

app/views/users/show.html.erb
 <div class="container px-5 px-sm-0">
   <div class="row">

     <%= render 'books/list', user: @user,book: @book %>

      <div class="col-md-8 offset-md-1">

        <h2>Books</h2>

        <table class="table table-hover table-inverse">
           <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
           </thead>
         <% @books.each do |book| %>
         <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
              <%= image_tag @user.get_profile_image(100,100) %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
              <%= book.title %>
              <% end %>
            </td>
            <td>
              <%= book.body %>
              <% end %>
            </td>
          </tr>
         </tbody>
        </table>

      </div>
   </div>
 </div>